app/controllers/events.py
from flask import Blueprint, flash, jsonify, redirect, render_template, request, url_for
from flask_jwt_extended import get_jwt_identity, jwt_required, verify_jwt_in_request
from flask_pydantic import validate
from app.db.models import UserRole
from app.db.repositories.event import EventRepository
from app.db.repositories.record import RecordRepository
from app.db.repositories.review import ReviewRepository
from app.db.repositories.user import UserRepository
from app.exception_handlers import CustomException
from app.schemas import EventCreateSchema, EventUpdateSchema, RecordCreateSchema, ReviewCreateSchema

event_blueprint = Blueprint("events", __name__)

repository = EventRepository()
user_repository = UserRepository()
review_repository = ReviewRepository()
record_repository = RecordRepository()

def event_middleware() -> None:
    role = user_repository.get_user_by_id(get_jwt_identity()).role
    if role != UserRole.ADMIN.value and role != UserRole.HOST.value:
        raise CustomException(
            message="У пользователя отсутствуют права", 
            status_code=403
        )


@event_blueprint.route('/', methods=['GET'])
def list():
    events = repository.get_events_all()
    try:
        verify_jwt_in_request()
        user = user_repository.get_user_by_id(get_jwt_identity())
        return render_template('events/event_list.html', events=events, user=user)
    except Exception as e:
        return render_template('events/event_list.html', events=events, user=None)


@event_blueprint.route('/', methods=['POST'])
@jwt_required()
def create():
    event_middleware()
    form_data = request.form.to_dict()
    created_event = repository.create_event(EventCreateSchema(**form_data))
    return redirect(url_for('events.list'))


@event_blueprint.route('/<int:event_id>', methods=['GET'])
def detail(event_id):
    event = repository.get_event_by_id(event_id)
    if not event:
        return CustomException(message="Не найдено мероприятие", status_code=404)
    return render_template('events/event.html', event=event)


@event_blueprint.route('/<int:event_id>/delete', methods=['GET'])
@jwt_required()
def delete(event_id):
    event_middleware()
    success = repository.delete_event(event_id)
    if not success:
        return CustomException(message="Не найдено мероприятие", status_code=404)
    return redirect(url_for("events.list"))


@event_blueprint.route('/<int:event_id>', methods=['POST'])
@jwt_required()
def update(event_id):
    event_middleware()
    form_data = request.form.to_dict()
    edited_event = repository.update_event(event_id, EventUpdateSchema(**form_data))
    if not edited_event:
        return CustomException(message="Event not found", status_code=404)
    return redirect(url_for('events.detail', event_id=edited_event))


@event_blueprint.route('/<int:event_id>/reviews', methods=['GET'])
def review_list(event_id):
    reviews = review_repository.get_reviews_all()
    try:
        verify_jwt_in_request()
        user = user_repository.get_user_by_id(get_jwt_identity())
        return render_template('events/reviews/review_list.html', reviews=reviews, user=user, event_id=event_id)
    except Exception as e:
        return render_template('events/reviews/review_list.html', reviews=reviews, user=None, event_id=event_id)


@event_blueprint.route('/<int:event_id>/reviews', methods=['POST'])
@jwt_required()
def create_review(event_id: int):

    user_id = get_jwt_identity()

    form_data = request.form.to_dict()
    form_data['user_id'] = user_id
    form_data['event_id'] = event_id
    review_id = review_repository.create_review(ReviewCreateSchema(**form_data))

    return redirect(url_for("events.review_list", event_id=event_id))


@event_blueprint.route('/<int:event_id>/reviews/<int:review_id>', methods=['GET'])
def review_detail(event_id, review_id):
    review = review_repository.get_review_by_id(review_id)
    if not review:
        raise CustomException(message="Не найден отзыв", status_code=404)
    return render_template('events/reviews/review.html', review=review)


@event_blueprint.route('/<int:event_id>/reviews/<int:review_id>/delete', methods=['GET'])
@jwt_required()
def review_delete(event_id, review_id):
    user = user_repository.get_user_by_id(get_jwt_identity())
    success = review_repository.delete_review(review_id)
    if not success:
        raise CustomException(message="Не найден отзыв", status_code=404)
    return redirect(url_for("events.review_list", event_id=event_id, user=user))


# Records routes
@event_blueprint.route('/<int:event_id>/records', methods=['GET'])
def record_list(event_id):
    records = record_repository.get_records_all()
    try:
        verify_jwt_in_request()
        user = user_repository.get_user_by_id(get_jwt_identity())
        return render_template('events/record_list.html', records=records, user=user, event_id=event_id)
    except Exception as e:
        return render_template('events/record_list.html', records=records, user=None, event_id=event_id)


@event_blueprint.route('/<int:event_id>/records', methods=['POST'])
@jwt_required()
def create_record(event_id):
    record = RecordCreateSchema(
        user_id=get_jwt_identity(),
        event_id=event_id
    )
    try:
        created_record = record_repository.create_record(record)
        flash(message="Запись успешно создана", category='success')
    except Exception as e:
        flash(message="Запись от вас уже создана", category='error')
    return redirect(url_for('events.record_list', event_id=event_id))


@event_blueprint.route('/<int:event_id>/records/<int:record_id>/delete', methods=['GET'])
@jwt_required()
def record_delete(event_id, record_id):
    success = record_repository.delete_record(record_id)
    if not success:
        raise CustomException(message="Не найдена запись", status_code=404)
    return redirect(url_for('events.record_list', event_id=event_id))

app/controllers/index.py
from flask import Blueprint, jsonify, make_response, redirect, render_template, request, url_for
from flask_jwt_extended import create_access_token, get_jwt_identity, jwt_required, set_access_cookies, verify_jwt_in_request
from flask_login import login_manager, login_user
from pydantic import ValidationError
from werkzeug.security import check_password_hash, generate_password_hash

from app.db.models import UserRole
from app.db.repositories.user import UserRepository
from app.exception_handlers import CustomException
from app.schemas import UserCreateSchema

main_blueprint = Blueprint("main", __name__)
repository = UserRepository()

@main_blueprint.route('/', methods=['GET'])
def index():
    try:
        # Пытаемся проверить наличие токена в запросе
        verify_jwt_in_request()
        user_identity = get_jwt_identity()
        user = repository.get_user_by_id(user_identity)
        return render_template('index.html', user=user)
    except Exception:
        # Если токен не передан или некорректен, передаем значение None для неаутентифицированного пользователя
        return render_template('index.html', user=None)
    

# Регистрация нового пользователя
@main_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        # Получаем данные из формы
        form_data = request.form.to_dict()

        # Проверка, существует ли пользователь с таким именем
        existing_user = repository.get_user_by_username(form_data["login"])
        if existing_user:
            raise CustomException(message="User login already exists", status_code=400, redirect_page="main.register")
        existing_user = repository.get_user_by_email(form_data["email"])
        if existing_user:
            raise CustomException(message="User email already exists", status_code=400, redirect_page="main.register")

        hashed_password = generate_password_hash(form_data['password'])

        try:
            user_schema = UserCreateSchema(**form_data)
            user_schema.password = hashed_password
        except ValidationError as e:
            raise CustomException(message="Invalid user data", status_code=422, redirect_page="main.register")
        
        user_id = repository.create_user(user_schema)
        
        return render_template('login.html')  # Перенаправление на страницу логина после регистрации
    
    return render_template('register.html')


@main_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form.get('login')
        password = request.form.get('password')

        user = repository.get_user_by_username(username)
        if user:
            if check_password_hash(user.password, password):
                # Создаем JWT
                access_token = create_access_token(identity=str(user.id))
                response = make_response(render_template("dashboard.html", user=user))
                # Сохраняем токен в cookie
                set_access_cookies(response, access_token)
                return response
            
        error_message = "Invalid username or password"
        return render_template('login.html', error=error_message)
        
    return render_template('login.html')


@main_blueprint.route('/dashboard', methods=['GET'])
@jwt_required()
def profile():
    user_id = get_jwt_identity()
    user = repository.get_user_by_id(user_id)
    if not user:
        return CustomException(message="User not found", status_code=404)
    
    return render_template('dashboard.html', user=user)


@main_blueprint.route('/logout', methods=['GET'])
@jwt_required()
def logout():
    response = make_response(render_template("index.html"))
    # Удаляем токен из cookies
    response.delete_cookie('access_token_cookie')
    return response

app/templates/events/event.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Просмотр мероприятия</title>
    {{bootstrap.load_css()}}
</head>
<body>
    <div class="container mt-5">
        <div class="card shadow-lg">
            <div class="card-header bg-primary text-white">
                <h2 class="card-title">Просмотр мероприятия</h2>
            </div>
            <div class="card-body">
                <div class="mb-4">
                    <label class="form-label text-muted"><strong>Название</strong></label>
                    <p class="border rounded p-3 bg-light">{{ event.title }}</p>
                </div>
                <div class="mb-4">
                    <label class="form-label text-muted"><strong>Описание</strong></label>
                    <p class="border rounded p-3 bg-light">{{ event.description }}</p>
                </div>
                <div class="mb-4">
                    <label class="form-label text-muted"><strong>Идентификатор организации</strong></label>
                    <p class="border rounded p-3 bg-light">{{ event.place_id }}</p>
                </div>
                <div class="mb-4">
                    <label class="form-label text-muted"><strong>Дата начала</strong></label>
                    <p class="border rounded p-3 bg-light">{{ event.started_at }}</p>
                </div>
                <div class="text-end">
                    <a href="{{ url_for('events.list') }}" class="btn btn-secondary">Назад</a>
                </div>
            </div>
        </div>
    </div>

    {{bootstrap.load_js()}}
</body>
</html>

app/templates/events/event_list.html
{% extends 'base.html' %}

{% block title %}Список мероприятий{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2>Список мероприятий</h2>
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Название</th>
                <th>Описание</th>
                <th>Идентификатор места</th>
                <th>Дата начала</th>
                <th>Действия</th>
            </tr>
        </thead>
        <tbody>
            {% for event in events %}
                <tr>
                    <td>{{ event.id }}</td>
                    <td>{{ event.title }}</td>
                    <td>{{ event.description }}</td>
                    <td>{{ event.place_id }}</td>
                    <td>{{ event.started_at }}</td>
                    <td>
                        <a href="{{ url_for('events.detail', event_id=event.id) }}" class="btn btn-info">Просмотр</a>
                        <a href="{{ url_for('events.review_list', event_id=event.id) }}" class="btn btn-info">Отзывы</a>
                        <a href="{{ url_for('events.record_list', event_id=event.id) }}" class="btn btn-info">Записи</a>
                        {% if user %}
                        {% if user.role == "ADMIN" or user.role == "HOST" %}
                        <a href="#" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#editEventModal{{ event.id }}">Редактировать</a>
                        <a href="{{ url_for('events.delete', event_id=event.id) }}" class="btn btn-danger">Удалить</a>
                        {%endif%}
                        {%endif%}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% if user %}
    {% if user.role == "ADMIN" or user.role == "HOST" %}
    <a href="#" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#createEventModal">Создать новое мероприятие</a>
    {%endif%}
    {%endif%}
    <a href="{{ url_for('main.index') }}" class="btn btn-danger">Выйти в главное меню</a>
</div>

<div class="modal fade" id="createEventModal" tabindex="-1" aria-labelledby="createEventModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="createEventModalLabel">Создание нового мероприятия</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
        </div>
        <div class="modal-body">
          <form action="{{ url_for('events.create') }}" method="POST">
            <!-- Название мероприятия -->
            <div class="mb-3">
              <label for="title" class="form-label">Название</label>
              <input type="text" id="title" name="title" class="form-control" required>
            </div>
  
            <!-- Описание мероприятия -->
            <div class="mb-3">
              <label for="description" class="form-label">Описание</label>
              <textarea id="description" name="description" class="form-control" required></textarea>
            </div>

            <div class="mb-3">
              <label for="place_id" class="form-label">Идентификатор организации</label>
              <input type="number" id="place_id" name="place_id" class="form-control" required></input>
            </div>
  
            <!-- Дата начала -->
            <div class="mb-3">
              <label for="started_at" class="form-label">Дата начала</label>
              <input type="datetime-local" id="started_at" name="started_at" class="form-control" required>
            </div>
  
            <!-- Кнопки -->
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
              <button type="submit" class="btn btn-primary">Создать мероприятие</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

{% for event in events %}
<div class="modal fade" id="editEventModal{{ event.id }}" tabindex="-1" aria-labelledby="editEventModalLabel{{ event.id }}" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editEventModalLabel{{ event.id }}">Редактирование мероприятия</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
            </div>
            <div class="modal-body">
                <form action="{{ url_for('events.update', event_id=event.id) }}" method="POST">
                    <div class="mb-3">
                        <label for="title" class="form-label">Название</label>
                        <input type="text" id="title" name="title" class="form-control" value="{{ event.title }}" required>
                    </div>
                    <div class="mb-3">
                        <label for="description" class="form-label">Описание</label>
                        <textarea id="description" name="description" class="form-control" required>{{ event.description }}</textarea>
                    </div>
                    <div class="mb-3">
                        <label for="started_at" class="form-label">Дата начала</label>
                        <input type="datetime-local" id="started_at" name="started_at" class="form-control" value="{{ event.started_at }}" required>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                        <button type="submit" class="btn btn-primary">Сохранить изменения</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endfor %}

{% endblock %}

app/templates/events/record_list.html
{% extends 'base.html' %}

{% block title %}Список отзывов{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2>Список записей</h2>
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Идентификатор пользователя</th>
                <th>Идентификатор мероприятия</th>
                <th>Дата создания записи</th>
                <th>Действия</th>
            </tr>
        </thead>
        <tbody>
            {% for record in records %}
                {% if record.event_id == event_id %}
                <tr>
                    <td>{{ record.id }}</td>
                    <td>{{ record.user_id }}</td>
                    <td>{{ record.event_id }}</td>
                    <td>{{ record.created_at }}</td>
                    <td>
                        {% if user %}
                        {% if user.id == record.user_id %}
                        <a href="{{ url_for('events.record_delete', record_id=record.id, event_id=event_id) }}" class="btn btn-danger">Удалить</a>
                        {% endif %}
                        {% endif %}
                    </td>
                </tr>
                {% endif %}
            {% endfor %}
        </tbody>
    </table>

    {% if error %}
    <div class="alert alert-danger mt-3 text-center" role="alert">
        <p>{{ error }}</p>
    </div>
    {% endif %}

    {% if user %}
    <!-- Кнопка для открытия модального окна создания отзыва -->
    <form action="{{ url_for('events.create_record', event_id=event_id) }}" method="POST">
        <button type="submit" class="btn btn-primary">Записаться на мероприятие</button>
    </form>
    {% endif %}
    <a href="{{ url_for('events.list') }}" class="btn btn-danger mt-3">Назад</a>
</div>

<!-- Модальное окно создания нового отзыва -->
<div class="modal fade" id="createRecordModal" tabindex="-1" aria-labelledby="createRecordModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="createRecordModalLabel">Создать новый отзыв</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
            </div>
            <div class="modal-body">
                <form action="{{ url_for('events.create_record', event_id=event_id) }}" method="POST">
                    <div class="mb-3">
                        <label for="event_id" class="form-label">Идентификатор мероприятия</label>
                        <input type="number" id="event_id" name="event_id" class="form-control" required>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                        <button type="submit" class="btn btn-primary">Создать</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}